/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
